name: rapid_delivery_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen: ^1.3.0
  lottie: ^3.1.0
  animated_text_kit: ^4.2.2
  google_fonts: ^6.2.1
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  firebase_storage: ^11.7.5
  cloud_firestore: ^4.17.3
  cupertino_icons: ^1.0.6
  dots_indicator: ^3.0.0
  flutter_sticky_widgets: ^0.0.3
  email_validator: ^2.0.1
  timelines: ^0.1.0
  timeline_tile: ^2.0.0
  intl_phone_field: ^3.1.0
  font_awesome_flutter: ^10.7.0
  google_maps_flutter: ^2.6.1
  url_launcher: ^6.2.6
  intl: ^0.19.0
  fl_chart: ^0.68.0
  geocoding: ^2.0.4
  geolocator: ^8.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - image/
    - image/login_background.png
    - image/valide.png

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
